---
- name: "Setup postgres_exporter (Ubuntu 20.04, Ubuntu 22.04)"
  hosts: postgres_exporter
  gather_facts: true
  become: true

  roles:
    - role: postgres_exporter
      # environment:
      #   http_proxy: "http://user:password@10.20.30.40:3128"
      #   https_proxy: "http://user:password@10.20.30.40:3128"
      #   HTTP_PROXY: "http://user:password@10.20.30.40:3128"
      #   HTTPS_PROXY: "http://user:password@10.20.30.40:3128"
      vars:
        postgres_exporter__version: "0.15.0"
        postgres_exporter__port: 9187
        postgres_exporter__pgsql_cluster_host: 127.0.0.1
        postgres_exporter__pgsql_cluster_port: 5432
        postgres_exporter__pgsql_cluster_create_monitor_user: true
        postgres_exporter__pgsql_cluster_monitor_user: monitor
        postgres_exporter__pgsql_cluster_monitor_user_password: password
        postgres_exporter__pgsql_cluster_admin_user: postgres
        postgres_exporter__pgsql_cluster_admin_password: password
