---
- name: "Add group etcd"
  ansible.builtin.group:
    name: etcd
    state: present
    system: true

- name: "Create user etcd \
    and add group etcd as primary"
  ansible.builtin.user:
    name: etcd
    group: etcd
    create_home: false
    system: true
    shell: /usr/sbin/nologin

- name: "Download etcd from GitHub"
  ansible.builtin.get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/\
      v{{ etcd__etcd_version }}\
      /etcd-v{{ etcd__etcd_version }}-linux-amd64.tar.gz"
    dest: "/tmp/etcd-v{{ etcd__etcd_version }}-linux-amd64.tar.gz"
    mode: "0644"
    owner: root
    group: root

- name: "Extract and install etcd"
  ansible.builtin.unarchive:
    src: "/tmp/etcd-v{{ etcd__etcd_version }}-linux-amd64.tar.gz"
    dest: "/usr/bin"
    remote_src: true
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    extra_opts:
      - --strip-components=1
      - "etcd-v{{ etcd__etcd_version }}-linux-amd64/etcd"
      - "etcd-v{{ etcd__etcd_version }}-linux-amd64/etcdctl"

- name: "Create etcd systemd service"
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: "0644"
    backup: true

- name: "Generate etcd's configuration file"
  ansible.builtin.template:
    src: "etcd.j2"
    dest: "/etc/default/etcd"
    owner: root
    group: root
    mode: '0644'
  # notify: "restart etcd service"

- name: "Create etcd's database directory"
  ansible.builtin.file:
    path: "{{ etcd__data_dir }}"
    state: directory
    mode: '0700'
    owner: etcd
    group: etcd

- name: "Start and enable etcd service"
  ansible.builtin.service:
    name: "etcd"
    state: started
    enabled: true
    daemon_reload: true
