---
- name: "Download postgres_exporter from GitHub"
  ansible.builtin.get_url:
    url: "https://github.com/prometheus-community/postgres_exporter/releases/\
      download/v{{ postgres_exporter__version }}\
      /postgres_exporter-{{ postgres_exporter__version }}.linux-amd64.tar.gz"
    dest: |-
      /tmp/postgres_exporter-{{ postgres_exporter__version }}.linux-amd64.tar.gz
    mode: "0644"

- name: "Install postgres_exporter"
  ansible.builtin.unarchive:
    src: |-
     /tmp/postgres_exporter-{{ postgres_exporter__version }}.linux-amd64.tar.gz
    dest: "/usr/local/bin"
    remote_src: true
    owner: "{{ __postgres_exporter__user }}"
    group: "{{ __postgres_exporter__group }}"
    mode: u=rwx,g=rwx,o=r
    extra_opts:
      - --strip-components=1
      - "postgres_exporter-{{ postgres_exporter__version }}.\
        linux-amd64/postgres_exporter"

- name: "Create directory /opt/postgres_exporter"
  ansible.builtin.file:
    path: "/opt/postgres_exporter"
    state: directory
    mode: '0644'
    owner: postgres
    group: postgres

- name: "Create file for additional queries for metrics"
  ansible.builtin.template:
    src: queries.yml.j2
    dest: "/opt/postgres_exporter/queries.yml"
    owner: postgres
    group: postgres
    mode: '0644'

- name: "Create user in postgresql cluster with permissions for monitoring"
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    port: "{{ postgres_exporter__pgsql_cluster_port }}"
    name: "{{ postgres_exporter__pgsql_cluster_monitor_user }}"
    password: "{{ postgres_exporter__pgsql_cluster_monitor_user_password }}"
    role_attr_flags: LOGIN
    conn_limit: -1
  when:
    - postgres_exporter__pgsql_cluster_admin_password is defined
    - postgres_exporter__pgsql_cluster_create_monitor_user

- name: "Add role for monitoring for created user"
  community.postgresql.postgresql_query:  # FIXME package?
    login_host: "{{ postgres_exporter__pgsql_cluster_host }}"
    login_user: "{{ postgres_exporter__pgsql_cluster_admin_user }}"
    login_password: "{{ postgres_exporter__pgsql_cluster_admin_password }}"
    db: postgres
    port: "{{ postgres_exporter__pgsql_cluster_port }}"
    query: |-
      GRANT pg_monitor to {{ postgres_exporter__pgsql_cluster_monitor_user }}
    autocommit: true
  when:
    - postgres_exporter__pgsql_cluster_admin_password is defined
    - postgres_exporter__pgsql_cluster_create_monitor_user

- name: "Create postgres_exporter systemd service"
  ansible.builtin.template:
    src: postgres_exporter.service.j2
    dest: "/etc/systemd/system/postgres_exporter_\
      {{ postgres_exporter__pgsql_cluster_port }}.service"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: "restart postgres_exporter"

- name: "Start and enable postgres_exporter systemd service"
  ansible.builtin.service:
    name: "postgres_exporter_{{ postgres_exporter__pgsql_cluster_port }}"
    state: started
    enabled: true
    daemon_reload: true
